### ISSUE TITLE
Startup fails because of dependency on MySQL

### ISSUE THREAD

**Issue by SaurabhVatsa** [mdelapenya/docker-liferay-portal#3]
While starting the image using "docker-compose up", even though MySQL starts before Liferay, It is not available by the time Liferay needs it.
Since Liferay is dependent on MySQL, the startup of Liferay fails. 
I tried using "wait-for-it" based on this reference, https://docs.docker.com/compose/startup-order/ . But I couldn't make it work. Any help would be great.

version : liferay-portal-7-ce-ga4-tomcat-mysql

**Comment by mdelapenya** [comment]
hey @SaurabhVatsa that's the expected behaviour, as Liferay Portal GA4 does not have a retry strategy for the datasource.

This feature has been added to the next release here: https://issues.liferay.com/browse/LPS-73667

You'll be able to configure a retry strategy adding two properties:

```properties
##
## Retry JDBC connection on portal startup.
##

    #
    # Set the number of seconds to retry getting a JDBC connection on portal
    # startup.
    #
    retry.jdbc.on.startup.delay=0

    #
    # Set the max number of times to retry getting a JDBC connection on portal
    # startup.
    #
    retry.jdbc.on.startup.max.retries=0
```

On the other hand, as we added support for configuring Liferay Portal with environment variables, you'll be able to add env_vars representing any portal prop. Please read this JIRA ticket carefully: https://issues.liferay.com/browse/LPS-72541

**Comment by SaurabhVatsa** [comment]
Hey @mdelapenya , thanks for the response. 
Docker documentation mentions that it is possible to delay the startup of one service until another service that it depends on, fires up. I was wondering if we can use/create something on that line and delay the startup of Liferay untill MySQL starts. 

For ex.
`version: "2"
services:
  web:
    build: .
    ports:
      - "80:8000"
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]
  db:
    image: postgres`

Though it is good to have this feature in the next release, is there a way to manually configure this in the current Version ?

**Comment by mdelapenya** [comment]
Yes, Docker documentation says that, but it waits for the main process, not for the custom logic expected by portal: so whenever the mysql container is up, portal will start, but it does not mean that the mysql database is already created.

**Comment by mdelapenya** [comment]
Hey @SaurabhVatsa, is this issue solved? If so, could you please close it. Thanks!
